title: Kyle Rodriguez
subtitle: Software Engineer
description: ""
url: "https://kyrod.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Contact
    url: /contact

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Kyle Rodriguez
author_bio: >-
  Hey there, I'm Kyle! I'm a software engineer from SoCal, currently living in Ann Arbor, Michigan. From 
  reverse engineering (aka destroying, whoops) a GameCube controller at age 7, to building my first PC in
  high school, I've always been passionate about working with and understanding how to use technology to 
  its maximum potential. When I'm not working on a new project or "fixing" my electronics with a hammer,
  you can probably find me playing or creating music in some capacity (working towards my first Spotify
  release one of these days). Let's get in touch over some (virtual) coffee!
author_email: "kyle@kyrod.com"
author_location: United States
author_website_url: https://kyrod.com
typewrite-text: Thinking of something clever to put here...

# Experiences
author_work_experiences:
  - company_name: Groundspeed Analytics
    company_logo: groundspeed.png
    company_url: https://groundspeed.com
    designation: Software Engineer (June 2019 - Present)
    description: >- 
      I design and build cloud-native systems which automate 
      and simplify time-consuming operational processes. I also work on maintaining reliable continuous
      integration and deployment pipeline, while developing comprehensive unit, integration,
      and load testing practices. Before moving into my engineering rols, I was a data analyst
      working with the machine learning team to develop highly-accurate QA automations.
    visibility: true

# Education
author_education_details:
  - college_logo: umich.png
    college_name: University of Michigan
    college_url: https://umich.edu
    college_degree: Economics, focus in Computer Science
    description: >-
      Bass Trombone Section Leader, Michigan Marching Band - Barger Leadership
      Institute Fellow - Residential College
    visibility: true

# Projects
author_project_details:
  - project_title: Goldify
    project_thumbnail: goldify.png
    project_description: >-
      This is a Spotify API based React application which allows users to create the
      perfect personal Spotify playlist! This project taught me first-hand how
      to design an app with user experience in mind, learning the ropes of React and
      working directly with users to create an enjoyable user experience.
    project_url: https://goldify.app
    visibility: true

  - project_title: Morning Catch-Up
    project_thumbnail: morningcatchup.png
    project_description: >-
      This project was my first real experience with python,
      as well as with creating a user-facing service. This app uses a Django backend
      and a python-based AWS Lambda function, which integrates with both Twitter and
      Reddit's APIs, to handle the daily data-gathering and
      publishing. While it's a bit rough around the edges, this project gave me a ton
      of knowledge around error-handling, security, webhosting, and working with
      public apis.
    project_url: https://morningcatchup.herokuapp.com
    visibility: true

# social links
github_username: kyrod
linkedin_username: kylemrodriguez

# formspree (contact form)
formspree_email: f/mbjqgjky

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show (can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: false

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
